Eng = int(input("Foundation English : "))
Bus = int(input("General Business : "))
Sys = int(input("Introduction to Computer Systems : "))
Comp = int(input("Computer Programming : "))
print("--- Your Score ---")
print(f"Foundation English : {Eng}")
print(f"General Business : {Bus}")
print(f"Introduction to Computer Systems : {Sys}")
print(f"Computer Programming : {Comp}")